# Generated by Django 2.0.6 on 2018-06-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
